- name: instalando o puppet na maquina devops
  package: 
   name: puppetserver
   update_cache: yes
  when: ansible_hostname == "devops"

- name: instalando puppet agent
  package:
   name: puppet-agent
   state: present
   update_cache: yes

- name: dando start no puppet agent quando for centos
  service:
   name: puppet
   state: started
  when: ansible_os_family == "RedHat"

