- name: criando os usuarios padroes para todas as maquinas
  user: 
   name: "{{item.nome}}"
   password: "{{item.senha}}"
   state: "{{item.estado}}"
   home: "{{item.casa}}"
  with_items:
    - { nome: eleni, senha: '$1$FkkOWdAG$PIC6zCRlOYJ4Oc8dwY6on1', estado: present, casa: /srv/eleni }
    - { nome: developer, senha: '$1$FkkOWdAG$PIC6zCRlOYJ4Oc8dwY6on1', estado: present, casa: /srv/developer }
    - { nome: devops, senha: '$1$FkkOWdAG$PIC6zCRlOYJ4Oc8dwY6on1', estado: present, casa: /srv/devops }
